<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CloseProductFilter</name>
   <tag></tag>
   <elementGuidId>4dc6aa34-aa30-42b8-a789-da148e99c91b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div/section/section/main/main/div/div[2]/div/div/form/div[3]/div/div/span/div/div/span[1]/i/svg/path</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div/section/section/main/main/div/div[2]/div/div/form/div[3]/div/div/span/div/div/span[1]/i/svg/path</value>
   </webElementProperties>
</WebElementEntity>
