<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DropDown_Products</name>
   <tag></tag>
   <elementGuidId>f9a5d199-a348-4d54-aee0-6e524db8d159</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div/section/section/main/main/div/div[2]/div/div/form/div[3]/div/div/span/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div/section/section/main/main/div/div[2]/div/div/form/div[3]/div/div/span/div/div/div</value>
   </webElementProperties>
</WebElementEntity>
