<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_HarvestDate</name>
   <tag></tag>
   <elementGuidId>7ab962b9-732b-4af4-8341-29965fb0c175</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div/div/div/div/div[2]/div[2]/table/tbody/tr[3]/td[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div/div/div/div/div[2]/div[2]/table/tbody/tr[3]/td[3]/div</value>
   </webElementProperties>
</WebElementEntity>
